# src/main/resources/application.yml
spring:
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      path: /api-docs
  flyway:
    baselineOnMigrate: true
    enabled: true
    locations: classpath:db.migration
  datasource:
    url: jdbc:postgresql://db:5432/demo
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
      show_sql: true
      globally_quoted_identifiers: true
      auto_quote_keyword: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema:
        show_sql: true
        ddl-auto: none
